apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexushr.fullname" . }}-db-pvc
  labels:
    app: {{ include "nexushr.name" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storageSize | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexushr.fullname" . }}-db
  labels:
    app: {{ include "nexushr.name" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nexushr.name" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "nexushr.name" . }}-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image | quote }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
          ports:
            - containerPort: 5432
              name: dbport
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "nexushr.fullname" . }}-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexushr.fullname" . }}-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "nexushr.name" . }}-db
